import { Contact } from "@/types/Contact"
import { calculateAge } from "@/utils/calculateAge"
import { sortByLastName } from "@/utils/sortByLastName"

const DEMONSTRATION_CONTACTS: Contact[] = [
  {
    id: 1,
    photo: "Unsplash Jessica Christian.png",
    firstName: "Jessica",
    lastName: "Christian",
    birthYear: "2022",
    birthMonth: "05",
    birthDay: "30",
    streetAddress: "1234 Main St",
    city: "San Francisco",
    state: "CA",
    zipCode: "94111",
    phoneNumber: "555-555-5555",
    email: "Jessica.Christian@fakeEmail.com",
  },
  {
    id: 2,
    photo: "Unsplash Lia Bekyan.png",
    firstName: "Lia",
    lastName: "Bekyan",
    birthYear: "2010",
    birthMonth: "09",
    birthDay: "24",
    streetAddress: "1234 Happy Lane",
    city: "San Diego",
    state: "CA",
    zipCode: "91911",
    phoneNumber: "555-555-5555",
    email: "Lia.Bekyan@fakeEmail.com",
  },
  {
    id: 3,
    photo: "Unsplash Remy Loz.png",
    firstName: "Remy",
    lastName: "Loz",
    birthYear: "2000",
    birthMonth: "07",
    birthDay: "04",
    streetAddress: "1234 Main St",
    city: "San Francisco",
    state: "CA",
    zipCode: "94111",
    phoneNumber: "555-555-5555",
    email: "Remy.Loz@fakeEmail.com",
  },
  {
    id: 4,
    photo: "Unsplash Ryan Hoffman.png",
    firstName: "Ryan",
    lastName: "Hoffman",
    birthYear: "1990",
    birthMonth: "04",
    birthDay: "06",
    streetAddress: "1234 Main St",
    city: "San Francisco",
    state: "CA",
    zipCode: "94111",
    phoneNumber: "555-555-5555",
    email: "Ryan.Hoffman@fakeEmail.com",
  },
  {
    id: 5,
    photo: "Unsplash Tadas Petrokas.png",
    firstName: "Tadas",
    lastName: "Petrokas",
    birthYear: "1956",
    birthMonth: "08",
    birthDay: "07",
    streetAddress: "1234 Main St",
    city: "San Francisco",
    state: "CA",
    zipCode: "94111",
    phoneNumber: "555-555-5555",
    email: "Tadas.Petrokas@fakeEmail.com",
  },
  {
    id: 6,
    photo: "Unsplash Yohan Marion.png",
    firstName: "Yohan",
    lastName: "Marion",
    birthYear: "1890",
    birthMonth: "11",
    birthDay: "24",
    streetAddress: "1234 Main St",
    city: "San Francisco",
    state: "CA",
    zipCode: "94111",
    phoneNumber: "555-555-5555",
    email: "Yohan.Marion@fakeEmail.com",
  },
]

export default function createDemonstrationContacts() {
  return DEMONSTRATION_CONTACTS.map((contact) => ({
    ...contact,
    age: calculateAge(contact),
  })).sort(sortByLastName)
}
